source ~/.antigen/antigen.zsh

antigen use oh-my-zsh
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle git
antigen bundle colorize 
antigen bundle colored-man-pages
antigen bundle command-not-found
antigen bundle clvv/fasd fasd
antigen bundle fasd
antigen bundle fzf
antigen bundle git-prompt

antigen theme denysdovhan/spaceship-prompt
antigen apply

ZSH_THEME="spaceship"
SPACESHIP_DIR_TRUNC=5
SPACESHIP_DIR_TRUNC_PREFIX="…/"
SPACESHIP_DIR_TRUNC_REPO="false"
SPACESHIP_VENV_SYMBOL="🐍·"
SPACESHIP_EXIT_CODE_SHOW="true"
SPACESHIP_EXIT_CODE_SYMBOL=""

zstyle ':completion:*' menu select 

# set ranger default editor
export EDITOR=vim ranger
export TERM=screen-256color
export LANG=en_US.UTF-8

# export MANPATH="/usr/local/man:$MANPATH"
# disable pasted text highlighting
zle_highlight+=(paste:none)

# Store npm packages in user space, no root
# might need to add prefix=${HOME}/.npm-packages to ~/.npmrc
# make sure ~/.npm-packages exists
NPM_PACKAGES="${HOME}/.npm-packages"
export PATH="$HOME/.npm-packages/bin:$PATH"

# Plugin conf -----------------
export _FASD_DATA="$HOME/.fasd_history"
DISABLE_AUTO_TITLE="true"
DISABLE_AUTO_UPDATE="true"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=244'
# initialize fasd
eval "$(fasd --init auto)"

export FZF_DEFAULT_OPS="--extended"
# export FZF_DEFAULT_COMMAND="fd --type f"
# export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
setopt HIST_IGNORE_ALL_DUPS

# use ctrl+o to navigate directories in ranger
function ranger-cd {
    tempfile="$(mktemp -t tmp.XXXXXX)"
    /usr/bin/ranger --choosedir="$tempfile" "${@:-$(pwd)}"
    test -f "$tempfile" &&
    if [ "$(cat -- "$tempfile")" != "$(echo -n `pwd`)" ]; then
        cd -- "$(cat "$tempfile")"
    fi  
    rm -f -- "$tempfile"
}
bindkey -s '^O' 'ranger-cd\n'

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# add cuda tools to command path
export PATH="/usr/local/cuda/bin:$PATH"
export MANPATH=/usr/local/cuda/man:${MANPATH}

# source ~/.rosrc

# Use android studio adb if available
if [[ -f "$HOME/Android/Sdk/platform-tools/adb" ]]; then
    alias adb="$HOME/Android/Sdk/platform-tools/adb" 
fi

alias clc='clear'
alias dirs='dirs -v'
alias d='dirs -v'
alias tree='tree -L 3 --filelimit 20 -h'
alias c='fasd -e code -d'
alias less='cless' # colored less 

# Freqtrade TA
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH