- name: Set up local development environment
  hosts: nexus
  roles:
    - {role: packages}
    # - {role: common}
    - {role: locale, tags: locale}
    - {role: tmux}
    - {role: zsh}
    - {role: vim}
    # # Tag each role so that we can select individual roles to run with ansible-playbook --tags