---

- debug:
    var: packages_to_install

- name: "Install packages"
  become: yes
  apt:
    pkg: "{{ packages_to_install }}"
    state: present
  # become_method: sudo

- name: Download LSD package
  get_url: 
    url: "https://github.com/Peltoche/lsd/releases/download/0.18.0/lsd_0.18.0_amd64.deb"
    dest: "/tmp/lsd.deb"

- name: "Install LSD package"
  become: yes
  apt:
    deb: "/tmp/lsd.deb"

- name: "Install ranger"
  pip:
    name: ranger-fm

- name: "ranger devicons plugin"
  git:
    repo: git@github.com:alexanderjeurissen/ranger_devicons.git
    dest: $HOME/.config/ranger/plugins/ranger_devicons
