---

- name: Check if symlink already exists
  stat: 
    path: "{{ dest }}"
  register: links

- name: Create backup dir
  file:
    path: {{ playbook_dir }}/backup
    state: directory
  when: links.stat.islnk is defined and links.stat.islnk

- name: Backup {{ dest }}
  command: mkdir -p {{ playbook_dir|quote }}/backup ; mv {{ dest|quote }} {{ playbook_dir|quote }}/backup/
  when: links.stat.islnk is defined and links.stat.islnk

- name: Create link for {{ src }}
  file: 
    src: "{{ src }}"
    dest: "{{ dest }}"
    state: link
    force: yes


