---

- name: Install zsh
  apt: name=zsh 
  become_method: sudo

- name: Create antigen dir
  file:
    path: "~/.antigen"
    state: directory

- name: Download antigen
  get_url:
    url: http://git.io/antigen
    dest: ~/.antigen/antigen.zsh

# - name: Link .zshrc
#   file:
#     src: "{{ playbook_dir }}/roles/zsh/files/zshrc"
#     dest: "~/.zshrc"
#     state: link

- import_tasks: safe_symlink.yaml
  vars: 
    src: "{{ playbook_dir }}/roles/zsh/files/zshrc"
    dest: "~/.zshrc"

- name: Get fzf
  git:
    repo: "https://github.com/junegunn/fzf.git"
    dest: "~/.fzf"

- name: Build fzf binary
  shell: "~/.fzf/install --bin"

- import_tasks: patched_fonts.yaml # should only have to be done on GUI

- name: Set default shell
  user: 
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh