---

- name: Install tmux apt
  apt: name=tmux state=present
  become_method: sudo

- name: Install tpm
  git: 
    repo: https://github.com/tmux-plugins/tpm
    dest: "~/.tmux/plugins/tmp"
  shell: "~/.tmux/plugins/tmp/scripts/install_plugins.sh"

- name: Link tmux.conf
  file:
    src: "tmux.conf"
    dest: "~/.tmux.conf"
    state: link
