---

- name: Install tmux apt
  apt: name=tmux state=present
  become_method: sudo

- name: Link tmux.conf
  file:
    src: "{{ playbook_dir }}/roles/tmux/files/tmux.conf"
    dest: "~/.tmux.conf"
    state: link

- name: Install tpm
  git: 
    repo: https://github.com/tmux-plugins/tpm
    dest: "~/.tmux/plugins/tmp"

- name: Install plugins
  shell: "~/.tmux/plugins/tmp/scripts/install_plugins.sh"

