---

- name: Create autoload dir
  file:
    path: "~/.vim/autoload" 
    state: directory

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "~/.vim/autoload/plug.vim"

- import_tasks: safe_symlink.yaml
  vars:
    src: "{{ playbook_dir }}/roles/vim/files/vimrc"
    dest: "~/.vimrc"

- name: Install plugins
  command: vim +PlugInstall +qall
