---

- name: Install vim
  apt: name=vim
  become_method: sudo

- name: Create autoload dir
  file:
    path: "~/.vim/autoload" 
    state: directory

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "~/.vim/autoload/plug.vim"

- name: Symlink vimrc
  file:
    src: "{{ playbook_dir }}/roles/vim/files/vimrc"
    dest: "~/.vimrc"
    state: link

- name: Install plugins
  command: vim +PlugInstall +qall
  when: vim_install_plugins|bool